$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths: [".gitignore", "*.lock", "target"]
dictionaryDefinitions: []
dictionaries: []
words: [
    # ===== Dev ===== #
    "deque",
    "nums",
    "recr", # recursive/recursion
    "strs",
    "subarray",
    "subarrays",
    # ===== Leetcode ===== #
    "koko",
    # ===== Resource ===== #
    "huahua's",
    "leetcode",
    "neet",
  ]
